### ISSUE TITLE
Compatibility with Synology Photos

### ISSUE THREAD

**Issue by jack-blackson** [gaudes/ioBroker.slideshow#116]
I wanted to ask if there are any plans to get Slideshow still working with Synology DSM 7.0 and the new Photos app? I know it is still very new, and don't know if there is an API available yet. Just wanted to show that there would be at least one happy user :)

**Comment by jack-blackson** [comment]
I checked for a description of a new API myself, but couldn't find someting. @gaudes do you see any chance or found any documentation on that yet?

**Comment by gaudes** [comment]
Hi @jack-blackson 

due to private reasons I have currently no time. My Synology is still running on DSM 6.X.

When I have more time, I will make an update of my DSM and then check it.

**Comment by totocotonio** [comment]
Hi,
ich hänge mich da mal ran. Auch ich habe auf dsm 7 umgestellt und gemerkt, das es nicht mehr funktioniert.

Ich würde mich freuen wenn du das fixen könntest, da ich die Slideshow sehr gerne nutze.

Gruß Torsten

**Comment by totocotonio** [comment]
Hi,
konntes Du schon was erreichen mit DSM 7

Gruß TM

**Comment by totocotonio** [comment]
Hi,
ich bekomme diese Meldung im LOG

`
slideshow.0 | 2022-02-19 14:37:48.299 | error | Error occured: Error getting pictures from Synology in Synology(updatePictureList/List)
`

**Comment by gaudes** [comment]
Hi @totocotonio ,
hast Du die Einstellungen des Adapters überprüft ? Sonst mach bitte mal ein Screenshot der Einstellungen.
Außerdem solltest die Berechtigungen des verwendeten Users prüfen.

**Comment by totocotonio** [comment]
![slide](https://user-images.githubusercontent.com/48123111/154817815-988489ef-c6c1-41e6-9a1d-658a4e330759.png)

Benutzer hat zugriff auf die Fotos

**Comment by gaudes** [comment]
@totocotonio : Kannst dich mal mit dem User direkt an Synology Photo anmelden ? Siehst Du die Bilder dann als "Persönlicher Speicherplatz" links oben oder als "Freigegebener Bereich" ?

**Comment by totocotonio** [comment]
Hi,
anmelden kann ich mich. Sehe aber keine Bilder, lustig.
In der Filestation kann ich ich sehen und öffnen in der Photostation sehe ich nichts.

**Comment by totocotonio** [comment]
So,
anmeldung in Photos ist möglich, Bilder sind zu sehen.
`
slideshow.0 | 2022-02-20 10:57:08.163 | error | Error occured: Error getting pictures from Synology in Synology(updatePictureList/List)
`
Immer noch der gleiche Fehler.

**Comment by gaudes** [comment]
Siehe oben:
@totocotonio : Kannst dich mal mit dem User direkt an Synology Photo anmelden ? Siehst Du die Bilder dann als "Persönlicher Speicherplatz" links oben oder als "Freigegebener Bereich" ?

**Comment by totocotonio** [comment]
Hi,
ja habe ich ja geschrieben. Ich sehe alles.

**Comment by jack-blackson** [comment]
Hab es auch gerade getestet, und bekomme das selbe Problem wie totocotonio, "error getting pictures from Synology".

**Comment by gaudes** [comment]
Sorry, der Benutzer muss Vollzugriff haben. Bitte auch direkt die Anmeldung mit dem Benutzer an Synology Photo testen.

**Comment by jack-blackson** [comment]
@gaudes  Wie meinst du Vollzugriff? Auf alle Fotos? Oder worauf?

**Comment by totocotonio** [comment]
@jack-blackson 
Ja in der Photostation musst du dem Benutzer "Vollzugriff" geben und und nicht nur teilrechte, dann funktioniert es.

**Comment by jack-blackson** [comment]
Und wie kann ich dann definiere, welche Fotos in der Slideshow angezeigt werden? Oder verstehe ich es falsch - Wo genau muss der Vollzugriff definiert werden?

**Comment by patti9000** [comment]
Ich schmeiß mich auch mal in die Testrunde. Musste den Benutzer, welche ich im Adapter hinterlegt habe, sogar in die Administratorengruppe heben. Dann funktionierte es. Aber wie @jack-blackson schon erwähnt, kann man dann die Fotos selektieren.
Ich hatte dem Benutzer nur Zugriff auf ein Album zugelassen, damit ich die Bilder auswählen kann, welche angezeigt werden. So holt er sich alle.

Aber es sollte auch positiv erwähnt werden, dass der prinzipielle Zugriff funktioniert! Großes Danke an @gaudes dafür!

**Comment by gaudes** [comment]
Hi zusammen,

also folgendes:

Die API ist etwas doof mittlerweile.

- Es wird zwischen "Persönlicher Bereich" und "Freigegebener Bereich" getrennt
- Wenn der Benutzer Vollzugriff hat ist der Zugriff auf die Fotos via API einfacher, außerdem können zukünftig eventuell mehr Filter eingebaut werden, z.B. Rating, Tags, ....
- Ohne Vollzugriff muss ich durch die Ordner iterieren, d.h. rekursiv alle Ordner anschauen ob dort Fotos drin sind. Da gibt es kaum Filtermöglichkeiten

Nun gibt es mehrere Varianten mit Vor- und Nachteilen:

**Variante 1: Der Benutzer hat Vollzugriff**
+ Zugriff auf Bilder ist über die API einfacher
+ API unterstützt alle Filterungen (Rating, Tags, Personen, ....) 
- Filterungen müssen in den Adapter integriert werden
- Benutzer braucht halt Vollzugriff

**Variante 2: Benutzer hat keinen Vollzugriff**
+ Benutzer hat Read-Only-Rechte
+ Einschränkung der Fotos erfolgt auf der Synology, nicht im Adapter
- Aufwendigere Programmierung der API-Zugriffe
- Filterungen kaum möglich, z.B. so wie es aussieht nicht nach Rating

**Variante 3: Kombination beider Varianten**
+ Bei Vollzugriff: Voller Zugriff möglich, sonst über einzelne Ordner
- Sehr aufwendige Programmierung, quasi Abbildung Variante 1 mit Fallback auf Variante 2
- Filterung würde bei Vollzugriff gehen, verstehen User den Unterschied? Abbildung in GUI?

Die aktuelle Version hier in GIT macht nur Variante 1. Ich habe mir Variante 2 angeschaut, geht auch, ist aber potenziell fehleranfälliger.

Was meint Ihr ?

Viele Grüße Ralf

P.S.: @patti9000 : Adminrechte braucht er für die Syno definitiv nicht. Vermutlich hatte der User keine Rechte für Photos.

**Comment by jack-blackson** [comment]
@gaudes  Ich weiß nicht wie es die Anderen den Adapter nutzen, aber für mich wäre es ausreichend, wenn ich nur Fotos aus einem Ordner sehen würde. Wäre es eine Möglichkeit, das wir hier einfach einen Link irgendwo eingeben können zu diesem Ordner? Dann müstest du nicht durchloopen und schauen, auf welchen Ordner du eine Berechtigung hast.

**Comment by patti9000** [comment]
@gaudes 
Kurze Frage noch zur aktuellen Umsetzung. Werden Fotos von freigegebenen und persönlichen Bereich abgefragt oder nur die vom persönlichen?
Mein ioBroker-User hat Lese-Schreibzugriff auf "photos" und Zugriff auf die Anwendung "Synology Photos", aber trotzdem kommt immer die Meldung "(483370) Error occured: Error getting pictures from Synology in Synology(updatePictureList/List)".
Der ioBroker-User hat bei mir keine Fotos im persönlichen Bereich, sondern nur ein Album im freigegebenen Bereich, welches vom Haupt-Account freigegeben wurde. Dieses sollte eben angezeigt werden.


Zu den Varianten:
Natürlich wäre es nett, wenn beide Varianten implementiert werden könnten, aber das führt vermutlich bei vielen zu Verwirrung bei der Handhabung.
Ich persönlich lege für externe Anwendungen, die Daten vom NAS benötigen, immer separate Nutzer an, welche nur auf den gewünschten Bereich Zugriff haben. Nicht mehr.
Somit dürfte für mich Variante 1 eigentlich reichen, wenn das Thema vom Anfang des Posts gelöst wurde.

mfg
Patti

**Comment by gaudes** [comment]
@patti9000 Meld dich bitte mal mit der verwendeten Kennung direkt an Synology Photos an, also an der Webseite. Geht das ? Siehst du Fotos ?

**Comment by patti9000** [comment]
@gaudes habe ich bereits geprüft. Ja, ich sehe die Fotos im freigegebenen Bereich. Der ioBroker-User ist im freigegebenen Ordner auch als "Manager" hinterlegt. Hier dürfte also auch keine Einschränkungen bestehen.

**Comment by gaudes** [comment]
@patti9000 Kannst mal einen Screenshot der Berechtigungen machen ?
Also am Photo als Admin anmelden, dann Einstellungen, Register "Freigegebener Bereich", Button "Zugriffsberechtigungen festlegen".

**Comment by patti9000** [comment]
@gaudes 
Dort gibt's auch nochmal Zugriffseinstellungen!? Ok, dort habe ich nicht den "Vollen Zugriff" eingestellt. Deshalb geht es nicht.

Ich weiß nicht wie das die anderen handhaben, aber eigentlich will ich, wie bereits oben erwähnt, dem User nicht auf alles Zugriff gewähren
![2022-02-26 22_32_14-Synology Photos – Microsoft​ Edge](https://user-images.githubusercontent.com/44667442/155859914-10ab13bc-9791-40a4-a9c8-0cd0a3496d1e.png)
.

**Comment by gaudes** [comment]
Somit würden alle Variante 2 bevorzugen ?

Variante 2: Benutzer hat keinen Vollzugriff

+ Benutzer hat Read-Only-Rechte
+ Einschränkung der Fotos erfolgt auf der Synology, nicht im Adapter
- Aufwendigere Programmierung der API-Zugriffe
- Filterungen kaum möglich, z.B. so wie es aussieht nicht nach Rating

Dann würde ich das so umbauen ?

**Comment by Azathoth88** [comment]
Ich hatte gerade probeweise getestet: Das Ganze scheint noch nicht wirklich zu funktionieren, oder?
Mein Testuser hatte innerhalb von Photos sogar Vollzugriff. Ich persönlich würde übrigens die Konfiguration über freigegebene Alben präferieren. Die Lösung ist aus meiner Sicht um einiges Charmanter. Insbesondere, weil man hier auf die Smart-Alben zurückgreifen könnte.

Idealerweise mit der Möglichkeit, dass man innerhalb des Adapters per Multi-Select oder zumindest per Drop-Down aus der Liste der freigegebenen Alben auswählen kann. Ich habe bestimmt über 20.000 Bilder auf Platte. Die Wahrscheinlichkeit, dass der Adapter über die bestehende Logik die für mich passenden Bilder findet ist damit überschaubar.

**Comment by manuxi** [comment]
Ich habe das jetzt auch einmal versucht, aber leider ohne Erfolg. Weder mit IP, IP+Port, Domain-Namen (ich benutze einen Reverse-Proxy + Lets-Encrypt-Zertifikat), Freigabe-Link, o.ä. 
Mir ist auch nicht klar, was der User für Berechtingungen erhalten soll. Habe in Synology Photos in dem entsprechenden Album nur die Möglichkeit, eine Freigabe zu erstellen, einen Syno-Nutzer auszuwählen und dem die Rechte entweder für Betrachter, Uploader oder Herunterladen zu geben. Please advice!
![image](https://user-images.githubusercontent.com/11303615/225179194-0b46dc6a-08d7-4911-9d67-c5825206c1c7.png)

**Comment by gaudes** [comment]
Hello,

after having no time for development a very long time I've just pushed new version 0.2.0 with a few changes.

Better support for DSM 7 and Start/stop control buttons included :-)

Kind regards

Ralf
