### ISSUE TITLE
Widget: cause memory leak

### ISSUE THREAD

**Issue by Scrounger** [gaudes/ioBroker.slideshow#125]
@gaudes 
Thanks for this great adapter.

I have unfortunately noticed that the widget causes a memory leak. Here is the error message:
![grafik](https://user-images.githubusercontent.com/6370451/134647100-c4027f69-0c12-4584-997c-48dca0ff74f3.png)
![grafik](https://user-images.githubusercontent.com/6370451/134647147-7d8a7921-0b6a-4fbb-bd72-cfdba766ce0c.png)

I got this error on
- raspberry pi 4 8GB with touch screen
- android 10 tablet (4GB)

I discoverd that the memory increase with every cycle image - it increase exactly on the size of the image.
![grafik](https://user-images.githubusercontent.com/6370451/134647479-b68aae5c-f508-4afa-a4f8-1fd1147c0c9e.png)
![grafik](https://user-images.githubusercontent.com/6370451/134647549-61603725-ddca-4fa7-939a-fdf0516a4630.png)
![grafik](https://user-images.githubusercontent.com/6370451/134647602-db322191-d870-4f20-9a2e-4178803189f4.png)
![grafik](https://user-images.githubusercontent.com/6370451/134647648-e1fbff38-26e5-45df-9abe-c32bba85e6fb.png)

Image are on a samba share that are mounted to my iobroker lxc and this folder used by the adapter.

**Comment by gaudes** [comment]
Hi @Scrounger 

I've just made a short test with Edge on Windows 10. The memory of my javascript-instance doesn't grow when changing pictures.

The widget code is not taking the pictures to memory. I update the img src object as integrated, decoded picture.

Can you test it on another device or with another webbrowser on this device ?

Regards, Ralf

**Comment by Scrounger** [comment]
@gaudes 
I made some test with chrome and firefox on android 10 tablet, same behavoiur.
Why you think that the widget not taking the image to the memory? 

I made a PR  #199  which seems to resolve this issue. I only changed to use a var for the image and reintialize it on every change.
![grafik](https://user-images.githubusercontent.com/6370451/158068641-d980495a-3f2f-4b8d-991a-0214641c69da.png)

**Comment by gaudes** [comment]
Reopen

**Comment by gaudes** [comment]
Reopen

**Comment by gaudes** [comment]
@Scrounger Thanks for your PR, I've merged the changes.
