### ISSUE TITLE
Kein Automatischer Start in der iOS Iobroker App

### ISSUE THREAD

**Issue by amnesia106** [gaudes/ioBroker.slideshow#13]
Der Automatische Start in die Slideshow view funktioniert nicht in der iobroker app auf dem iPad. in Safari hingeben funktioniert es

**Comment by gaudes** [comment]
Hi,

ja, in der iOS-App kann ich es nachvollziehen, es geht einfach nicht.

Leider ist die App "closed-source", d.h. ich kann nicht schauen warum es nicht geht.

Ich versuche mal rauszufinden ob es da einen Entwickler oder Support gibt.

**Comment by gaudes** [comment]
Hi @amnesia106 

ich habe es bei mir getestet.

Auf dem iPad startet die Slideshow sowohl in Safari als auch in der App problemlos.

Kannst mal einen Screenshot der Einstellungen der App posten ? Nur den unteren Bereich mit den Optionen, also da wo es mit "Batteriestatus in vis.0 aktivieren" los geht.

**Comment by gaudes** [comment]
Hi @amnesia106 

brauchst Du hier noch Unterstützung oder klappt es mittlerweile ?

VG Ralf
