### ISSUE TITLE
Feature Request: Start Image

### ISSUE THREAD

**Issue by Solilord** [gaudes/ioBroker.slideshow#138]
Hey! 

I would love to set a Start Image. 
In my situation i think the start image is always random. 

Thanks!

**Comment by gaudes** [comment]
Hi @Solilord 

can you show me your complete settings ?

Thanks and regards, Ralf

**Comment by Solilord** [comment]
![89BE5CF6-8D90-472A-9753-DC9C38E09421](https://user-images.githubusercontent.com/8177636/151679037-288d2437-0b80-4739-83ef-3468d22fda04.png)

Sorry. Hab’s grad nur vom Handy 😅

**Comment by gaudes** [comment]
Hi @Solilord 

welches Bild als erstes Bild angezeigt wird hängt ja von den Einstellungen im Adapter ab, diese meinte ich :-)

**Comment by Solilord** [comment]
Hi @gaudes  

Danke schonal für Deine Mühe!

Ach die meinst Du:

![grafik](https://user-images.githubusercontent.com/8177636/151679143-b94bac29-6b03-423c-9ddb-40d08da7dd81.png)

Es wird tatsächlich immer ein anderes Bild zum start gezeigt

**Comment by gaudes** [comment]
@Solilord 

"Start" ist relativ :-)

Schlussendlich legt ja der Adapter das aktuelle Bild fest, das Widget zeigt nur an was ihm der Adapter gibt.

Der Adapter liest also beim Start alle Bilder und schreibt diese gemäß Einstellung dann nach und nach in den Datenpunkt fürs Widget.

Es gibt also keine Möglichkeit dass das Widget immer ein "Startbild" hat, da der Adapter ja eventuell z.B. mehrere Widgets bedienen könnte.

**Comment by Solilord** [comment]
Ja ich dachte auch eher daran, dass das dann im widget passieren könnte. 
Aber da das ja wie Du schon sagst durch den adapter gesteuert wird wird das dann nix. 

Ist nicht so wild.

Danke Dir! :)

**Comment by gaudes** [comment]
Gerne, dann schließe ich das Issue.
