### ISSUE TITLE
Netzlaufwerk nicht unterstützt?

### ISSUE THREAD

**Issue by Schorlewalker** [gaudes/ioBroker.slideshow#14]
Hallo!

Ich habe ein privates Netzlaufwerk auf einem NUC bei mir. 
Ist es auch irgendwie möglich auf Bilder von dort zuzugreifen?
Wäre super!

(nicht wirklich ein bug, eher eine Anfrage oder Verständnisfrage, ob sowas vielleicht auch so schon geht! :-) )
VG
Jens

**Comment by gaudes** [comment]
Hi,

Netzlaufwerke sind sehr Betriebssystemabhängig, das ist unter Windows ganz anders zu machen als unter Linux. Daher habe ich es nicht direkt eingebaut.

Du kannst je nach OS aber z.B. bei Linux selbst einfach ein Mount auf das Share machen und dann in den Adaptereinstellungen einfach den Mount-Pfad angeben. Musst nur schauen dass die Berechtigungen passen.

VG Ralf

**Comment by Schorlewalker** [comment]
Okay, klar...
Hab iobroker im Docker laufen, mal schaun, ob/wie das dann geht. ;-)
Danke für den Anstoß...

**Comment by gaudes** [comment]
Probier den Mount mal im darunterliegenden OS und dann in den Container durchzureichen. Ist vermutlich einfacher.

**Comment by gaudes** [comment]
Hi @Schorlewalker 

passt es dann soweit ? Kann der Issue geschlossen werden ? Danke.

**Comment by Schorlewalker** [comment]
hi!

sorry, ich schaue, dass ich es heute getestet bekomme... :-)

gaudes ***@***.***> schrieb am Di., 6. Apr. 2021, 20:48:
