### ISSUE TITLE
info Felder vs. Bild

### ISSUE THREAD

**Issue by SteffnVo** [gaudes/ioBroker.slideshow#151]
Beim Anzeigen der Bilder (Bing) sind die Texte info1-3 immer eins hinterher. Die Beschreibung des Bilder ist quasi immer vom vorangegangenen Bild. Sehe auch keine Möglichkeit das einzustellen.

**Comment by gaudes** [comment]
Hey @SteffnVo ,

ich habe das ganze gerade getestet, bei mir passt es.

Welche Version des Adapters ? Hast Du den Adapter mal neu gestartet ?
