### ISSUE TITLE
[Feature Request] Random Order should not show current img again as next img

### ISSUE THREAD

**Issue by Acgua** [gaudes/ioBroker.slideshow#165]
Hi,

This adapter is awesome, thank you very much!  I am currently testing with just 5 images and works great so far.

As a feature request:

While testing the "random" option, it happens that the current image is being displayed again as the next image, which makes sense, since the random order function has chosen that current image as to be shown next again.

It looks to me the randomization is being done in : `/src/modules/slideFS.ts` 
```js
// See https://stackoverflow.com/questions/2450954/how-to-randomize-shuffle-a-javascript-array
for (let i = CurrentImages.length - 1; i > 0; i--) {
	const j = Math.floor(Math.random() * (i + 1));
	[CurrentImages[i], CurrentImages[j]] = [CurrentImages[j], CurrentImages[i]];
}
```

However, it would be great if this loop would remove current image object from the images array which is being randomized with above code. (and include fallback if just one image was defined, of course).

This would avoid showing the current image again as next image.

Thanks.
Happy to help with a function, if needed. Just need to further understand how the object `CurrentImages`  looks like.

**Comment by gaudes** [comment]
Hey @Acgua 

are you sure ? The Adapter reads all the pictures on startup in an array and is doing the randomization on this array only once.

The pictures are show from the array, which is already randomized. Maybe you have a duplicate picture in your directory ?
