### ISSUE TITLE
Web-Adapter Crash

### ISSUE THREAD

**Issue by n3roGit** [gaudes/ioBroker.slideshow#167]
I noticed that the adapter sends a request to the web server every 20ms. This may be forcing my Web.Adapter to restart.

This has already been discussed here:
https://github.com/ioBroker/ioBroker.proxy/issues/66#issuecomment-1021099894

Can you make the update time definable here in the adapter?

**Comment by Apollon77** [comment]
@gaudes Any idea why we saw requests roughly every 20ms ?

**Comment by n3roGit** [comment]
I am a fool. I read the log wrong. It must be my motioneye and not this adapter. Thus I close this issue.
