### ISSUE TITLE
Start Error

### ISSUE THREAD

**Issue by n3roGit** [gaudes/ioBroker.slideshow#208]
Hi,
I noticed that the adapter is always red and does not start. In the log I could find the following.

`<html>
<body>

host.iobroker | 2022-04-01 12:57:26.242 | info | Rebuild for adapter system.adapter.slideshow.0 not successful in 3 tries. Adapter will not be restarted again. Please execute "npm install --production" in adapter directory manually.
-- | -- | -- | --
host.iobroker | 2022-04-01 12:57:26.242 | error | instance system.adapter.slideshow.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.iobroker | 2022-04-01 12:57:26.242 | error | Caught by controller[0]: }
host.iobroker | 2022-04-01 12:57:26.242 | error | Caught by controller[0]: ]
host.iobroker | 2022-04-01 12:57:26.242 | error | Caught by controller[0]: '/opt/iobroker/node_modules/iobroker.slideshow/build/main.js'
host.iobroker | 2022-04-01 12:57:26.242 | error | Caught by controller[0]: '/opt/iobroker/node_modules/iobroker.slideshow/build/modules/global-helper.js',
host.iobroker | 2022-04-01 12:57:26.241 | error | Caught by controller[0]: requireStack: [
host.iobroker | 2022-04-01 12:57:26.241 | error | Caught by controller[0]: code: 'MODULE_NOT_FOUND',
host.iobroker | 2022-04-01 12:57:26.241 | error | Caught by controller[0]: at Module.require (internal/modules/cjs/loader.js:974:19) {
host.iobroker | 2022-04-01 12:57:26.241 | error | Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:790:12)
host.iobroker | 2022-04-01 12:57:26.241 | error | Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:950:32)
host.iobroker | 2022-04-01 12:57:26.241 | error | Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
host.iobroker | 2022-04-01 12:57:26.241 | error | Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:1085:14)
host.iobroker | 2022-04-01 12:57:26.240 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.slideshow/build/modules/global-helper.js:32:25)
host.iobroker | 2022-04-01 12:57:26.240 | error | Caught by controller[0]: at require (internal/modules/cjs/helpers.js:101:18)
host.iobroker | 2022-04-01 12:57:26.240 | error | Caught by controller[0]: at Module.require (internal/modules/cjs/loader.js:974:19)
host.iobroker | 2022-04-01 12:57:26.240 | error | Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:746:27)
host.iobroker | 2022-04-01 12:57:26.240 | error | Caught by controller[0]: at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
host.iobroker | 2022-04-01 12:57:26.240 | error | Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.slideshow/build/main.js
host.iobroker | 2022-04-01 12:57:26.239 | error | Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.slideshow/build/modules/global-helper.js
host.iobroker | 2022-04-01 12:57:26.239 | error | Caught by controller[0]: Require stack:
host.iobroker | 2022-04-01 12:57:26.239 | error | Caught by controller[0]: Error: Cannot find module '@sentry/types'
host.iobroker | 2022-04-01 12:57:26.239 | error | Caught by controller[0]: ^
host.iobroker | 2022-04-01 12:57:26.239 | error | Caught by controller[0]: throw err;
host.iobroker | 2022-04-01 12:57:26.238 | error | Caught by controller[0]: internal/modules/cjs/loader.js:905

</body>
</html>`

**Comment by gaudes** [comment]
Hi @n3roGit 

This looks like a defect installation of the adapter.

Please try remove und install again.

Regards, Ralf

**Comment by n3roGit** [comment]
At the moment I have only tried a second instance. But it's not working.

Better try to full remove and reinstall?

**Comment by n3roGit** [comment]
I just completely uninstalled the adapter and recreated it. Same problem.

**Comment by n3roGit** [comment]
Any ideas?

**Comment by gaudes** [comment]
Hi @n3roGit ,

which OS ? Which version of node ?
Never seen such errors, looks like a defect installation of node or so.

**Comment by n3roGit** [comment]
![image](https://user-images.githubusercontent.com/8565847/161961542-fe5de5b6-162d-4911-a072-4c843ed3ab93.png)
![image](https://user-images.githubusercontent.com/8565847/161961596-fad8c55a-a684-447d-af65-22255a158bc9.png)


All other plugins run without errors. only this one has stopped working. I have already performed a reinstallation. Can I provide more details to get to the bottom of the problem?

**Comment by n3roGit** [comment]
any ideas?

**Comment by n3roGit** [comment]
Since the adapter is not currently running on me I have temporarily bypassed it with a blockly.

`<xml xmlns="https://developers.google.com/blockly/xml">
  <variables>
    <variable type="interval" id="Intervall">Intervall</variable>
    <variable id="=p=yxmg}GLf@8PKVjkuf">result</variable>
  </variables>
  <block type="timeouts_setinterval" id="QZddM[t|*V_kN$/.Ggdq" x="-187" y="162">
    <field name="NAME">Intervall</field>
    <field name="INTERVAL">30</field>
    <field name="UNIT">sec</field>
    <statement name="STATEMENT">
      <block type="exec" id="Eu=H@X}Kfl%J?PfVmus|">
        <mutation xmlns="http://www.w3.org/1999/xhtml" with_statement="true"></mutation>
        <field name="WITH_STATEMENT">TRUE</field>
        <field name="LOG">log</field>
        <value name="COMMAND">
          <shadow type="text" id="lP1U.!KJk|(.Q1te(#o`">
            <field name="TEXT">ls /opt/iobroker/iobroker-data/files/vis.0/screensaver/* | sed  -e 's/$/;/' -e 's/\/opt\/iobroker\/iobroker-data\/files//'|tr --delete '\n'</field>
          </shadow>
        </value>
        <statement name="STATEMENT">
          <block type="control_ex" id="65#;t$2*i*]5m~E7C@,N">
            <field name="TYPE">false</field>
            <field name="CLEAR_RUNNING">FALSE</field>
            <value name="OID">
              <shadow type="field_oid" id="f[[MGLi/jZs#}`)|Fem@">
                <field name="oid">0_userdata.0.GlobalVars.screensaver_img</field>
              </shadow>
            </value>
            <value name="VALUE">
              <shadow type="logic_boolean" id="-8kcJp%AG~)WaY1ufNlr">
                <field name="BOOL">TRUE</field>
              </shadow>
              <block type="lists_getIndex" id="dVR#ei5CeZ;9i;J5:z$3">
                <mutation statement="false" at="false"></mutation>
                <field name="MODE">GET</field>
                <field name="WHERE">RANDOM</field>
                <value name="VALUE">
                  <block type="lists_split" id="]U?;56i:23kk2t.x2NEd">
                    <mutation mode="SPLIT"></mutation>
                    <field name="MODE">SPLIT</field>
                    <value name="INPUT">
                      <block type="variables_get" id="Z/YW:rTvo=$H/U5vty]E">
                        <field name="VAR" id="=p=yxmg}GLf@8PKVjkuf">result</field>
                      </block>
                    </value>
                    <value name="DELIM">
                      <shadow type="text" id="khuo},P#c*#x/u_x%v72">
                        <field name="TEXT">;</field>
                      </shadow>
                    </value>
                  </block>
                </value>
              </block>
            </value>
            <value name="DELAY_MS">
              <shadow type="math_number" id="cr%:uq!Kpy$`_;(bz6AP">
                <field name="NUM">0</field>
              </shadow>
            </value>
          </block>
        </statement>
      </block>
    </statement>
  </block>
</xml>`

now i only use your widget. however, i hope that this bug will still be fixed.

**Comment by n3roGit** [comment]
I don't know what it was. after the last updates from ioBroker the adapter works again.
