### ISSUE TITLE
IoBroker.vis app is not working

### ISSUE THREAD

**Issue by w-hayek** [gaudes/ioBroker.slideshow#238]
Hi,

Great adapter. 
Unfortunately it is not working with IoBroker.vis app.

Many thanks
Wassim

**Comment by gaudes** [comment]
Hi,

is this the android app?

I dont't own an android device, so I can't test.

Are there any error messages?

Regards, Ralf

**Comment by w-hayek** [comment]
Hi,
yes, an android app for Vis, here the link (the app is also available for ios):
https://play.google.com/store/apps/details?id=net.iobroker.vis&hl=de&gl=US

No error messages, just black screen!

Regards
Wassim

**Comment by gaudes** [comment]
Hi,

can you test it with a normal web browser on your device ?
When this works, maybe you can make an issue for the app developer ?

Regards, Ralf
