### ISSUE TITLE
start/stop/picname/etc

### ISSUE THREAD

**Issue by djmarc75** [gaudes/ioBroker.slideshow#276]
Super Adapter und funktioniert blendend wie er soll!

Ich würde mir wünschen dass man die Slideshow mit play/pause steuern könnte.
Ich nutze mounts und da es mal sein kann dass in einem Mountverzeichnis 1000+ Bilder drin stecken wirft es mir im Log (wenn ein Update der Picturelist startet) Fehler aus:

<html><body>

  | Error occured: File not accessible: /var/media/slideshow/**xxx**.jpg in Filesystem(getPicture)
-- | --

</body>
</html>

Daher wäre ein Pausieren, Stoppen und Starten-DP schon recht praktisch.
Ebenso würde ich mich freuen wenn die Bildernamen in einem DP erscheinen würden da dies u.U. in VIS gut verarbeitet werden kann.

Greets und es eilt ja nicht :)

**Comment by gaudes** [comment]
Hello,

after having no time for development a very long time I've just pushed new version 0.2.0 with a few changes.

Start/stop control buttons included :-)

Kind regards

Ralf
