### ISSUE TITLE
Local updatePictureList erweitert jedes mal das CurrentImages Array, anstatt es neu aufzusetzen

### ISSUE THREAD

**Issue by BasWeg** [gaudes/ioBroker.slideshow#30]
Hallo,
wenn "updatepicturelist" aufgerufen wird, wird das bestehende Array CurrentImages erweitert. 
PicturesCount inkrementiert dadurch jedes mal mit der Anzahl der Bilder im Verzeichnis. 12 -> 24 -> 36 ->....

Bei "updatepicturelist" solle das Array neu initialisiert werden, bevor es erweitert wird, oder?
 
https://github.com/gaudes/ioBroker.slideshow/blob/d83512fb9e73ccf612d3ba28bfc978bcb5e83a7b/build/modules/slideLocal.js#L34

Viele Grüße
Bastian

**Comment by gaudes** [comment]
Hi,

korrekt, danke für die Info.

Ich habe die Funktionen angepasst, nun wird das Array zuerst neu initialisiert.

VG Ralf

**Comment by BasWeg** [comment]
Hallo Ralf,
super, Dankeschön! 
Wann wird denn die Änderung in ioBroker sichtbar, oder muss ich das manuell reinziehen?
VG
Bastian

**Comment by gaudes** [comment]
@BasWeg Ich mach grad noch paar Änderungen und schiebe vermutlich nachher dann Version 0.1.3

Aktualisieren musst es dann aus dem Beta-Repository oder per Katze direkt von GitHub.

Melde mich wenn die Version final ist.

**Comment by gaudes** [comment]
@BasWeg : Version 0.1.3 ist veröffentlicht.
