### ISSUE TITLE
Update stable version in repo from 0.0.0 to 0.1.4

### ISSUE THREAD

**Issue by GermanBluefox** [gaudes/ioBroker.slideshow#311]
# Think about adding version 0.1.4 to stable repository.
**Version**: stable=**0.0.0** (0 days old) => latest=**0.1.4** (799 days old)
**Installs**: stable=**0** (0%), latest=**272** (95.77%), total=**284**
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json)

**Comment by gaudes** [comment]
Currently staying at Beta state
