### ISSUE TITLE
Optionale Zufallswiedergabe

### ISSUE THREAD

**Issue by heymkeyu** [gaudes/ioBroker.slideshow#37]
Hi, 
cooler Adapter. Genau das, was ich gesucht habe!

Ein Wunsch: Optionale Zufallswiedergabe.
Bei mir liegen > 5000 Bilder gesammelt über die Jahre in einem Verzeichnis. 
Da wäre es schön, wenn man eine Zufallswiedergabe konfigurieren könnte.

**Comment by gaudes** [comment]
Hi,
für welche Bildquelle ? Bei Synology gibt es das schon.
VG Ralf

**Comment by heymkeyu** [comment]
Oh, sorry, Filesystem.

**Comment by heymkeyu** [comment]
Das wäre top auch für Filesystem
![image](https://user-images.githubusercontent.com/48991539/114088840-bcdc7880-98b5-11eb-8767-3b2df0189ac3.png)
:-)

**Comment by gaudes** [comment]
Hallo,
ich habe es gerade eingebaut. Bitte mal testen und Rückmeldung geben.
Es ist keine neue Version, also Aktualisierung über die Katze --> Beliebig und dann folgendes eingeben:

`gaudes/ioBroker.slideshow#main`

Bitte Rückmeldung ob es so klappt.

**Comment by heymkeyu** [comment]
Hat geklappt, der Teil funktioniert wie er soll - vielen Dank!

Allerdings wurde dadurch https://github.com/gaudes/ioBroker.slideshow/issues/40 deutlicher sichtbar. 

Ich muss morgen mal gezielt das Bilder-Verzeichnis nochmals neu zusammenstellen um zu analysieren, ob es mit den Quellbildern ein erkennbares Muster gibt. 

Eine Auffälligkeit: Da sind sehr kleine Panoramabilder dabei (~100kb) aber auch sehr große von der digitalen Spiegereflex, die anschließend gestitcht wurden mit > 20BM. 

Melde mich. Vielen Dank einstweilen!

**Comment by heymkeyu** [comment]
Zufall passt. Das hier kann denke ich zu. :-)
