### ISSUE TITLE
ZoomToFit bei Querformat

### ISSUE THREAD

**Issue by heymkeyu** [gaudes/ioBroker.slideshow#38]
Wenn der ausgewählte Bildbereich breites Querformat ist, dann 

- funktionieren Hochformat-Bilder im ZoomToFit korrekt (schwarz im Beispiel)
- sind Querformat-Bilder zwar in die Breite eingepasst, die oberen und unteren Kanten der Bilder jedoch abgeschnitten, so dass wichtige Teile des Bildes fehlen. Die korrekte Darstellung wäre der rote Kasten
- Panoramabilder sollten wie blau dargestellt links und rechts eingepasst werden. 

Beispiel für den Bildbereich:
![image](https://user-images.githubusercontent.com/48991539/114087238-ebf1ea80-98b3-11eb-9138-272d1a5d25e3.png)

Bei allen Formaten sollten also keine Beschneidungen stattfinden, sondern jeweils ein ZoomToFit.

**Comment by gaudes** [comment]
Nochmal hallo,

jetzt sind wir im Bereich "Geschmackssache" :-)

Ich habe es mit Absicht so gemacht. Ich wollte gerade im Querformat bei mir Display-füllende Bilder ohne schwarze Trauerränder.

Bei mir gehen meist nur ein paar Prozent des Bilder verloren, da ist dann ehrlich gesagt selten was wichtiges drauf.

Ich würde den Issue mal stehen lassen, mal schauen ob es noch andere so sehen, OK ?

**Comment by jack-blackson** [comment]
Ich hab mir heute das selbe gedacht - es wäre super, wenn bei normalen Querformatbildern  alles sichtbar wäre, auch wenn es bedeutet, das etwas Rand sichtbar ist. Bzw. wenn es eine Option im Widget ist?

**Comment by heymkeyu** [comment]
> Option im Widget ist?

Das ist der Weg. ;-)

**Comment by gaudes** [comment]
Hallo,
ich habe es gerade eingebaut. Bitte mal testen und Rückmeldung geben.
Es ist keine neue Version, also Aktualisierung über die Katze --> Beliebig und dann folgendes eingeben:

gaudes/ioBroker.slideshow#main

Bitte Rückmeldung ob es so klappt.

**Comment by heymkeyu** [comment]
In der Edit-Ansicht wird die Funktion der Checkbox "Widget mit Bild füllen" noch nicht klar, da das Bild nach Änderung nicht anders im Widget eingepasst wird.

In der Visualisierungs-Darstellung passt es.

Top! Danke. :-)

**Comment by gaudes** [comment]
Ich hab jetzt nicht so den großen Wert drauf gelegt dass es in der Edit-Ansicht voll funktioniert. Denk es passt wenn es dann in der normalen Darstellung korrekt ist.

Ich mach das Issue zu.
