### ISSUE TITLE
EXIF-Properties als Datenpunkte anbieten

### ISSUE THREAD

**Issue by heymkeyu** [gaudes/ioBroker.slideshow#39]
Schön wäre es, wenn der Adapter EXIF-Properties als Datenpunkte anbieten würde.

Idee dahinter: In der Visualisierung können diese als Feld platziert werden, um beispielsweise (insbesondere) das Aufnahmedatum darzustellen.

**Comment by gaudes** [comment]
Hi @heymkeyu 

siehe Tabelle in der Readme, es werden bereits einzelne Exif-Daten als Datenpunkte bereitgestellt.

**Comment by heymkeyu** [comment]
Super, das hatte ich übersehen. Passt so. Vielen Dank!
