### ISSUE TITLE
Bilder werden bei längerer Laufzeit unscharf / reduziert in der Qualität

### ISSUE THREAD

**Issue by heymkeyu** [gaudes/ioBroker.slideshow#40]
Ich habe > 5000 Bilder im FS. 

Nach rund 12h Laufzeit werden die Bilder bei der Anzeige unscharf / reduziert in der Qualität.
Habe während der Laufzeit mit unterschiedlichen Fading Effekten experimentiert. 
Nach Drücken des UpdatePictureList-Button ist die Schärfe wieder normal.

**Comment by gaudes** [comment]
Hi @heymkeyu 

also von mir kommt es nicht. Da läuft ja immer der exakt gleiche Code.

Hat das Anzeigedisplay vielleicht eine Funktion, so quasi als eigener Bildschirmschoner ?

**Comment by heymkeyu** [comment]
Kann ich mir nicht erklären. Das war auf unterschiedlichsten Devices zu sehen.
1 Lenovo Tab 4 8 Plus mit FullyKioskBrowser
2 Samsung A7 mit FullyKioskBrowser
1 Laptop FHD mit Chrome 

Heute hatte ich einen Fall, da habe ich die Situation einfach ignoriert und nach 1-2 Stunden hatte sich das Problem von selbst erledigt. 

Und dieser Teil ist mekrwürdig:
> Nach Drücken des UpdatePictureList-Button ist die Schärfe wieder normal.

Ich beobachte weiter.

**Comment by heymkeyu** [comment]
Weitere Infos dazu:
Screenshot vom lenovo Tablet:
![Screenshot_2021-04-10-07-11-38-771](https://user-images.githubusercontent.com/48991539/114259568-21d7c180-99cf-11eb-950d-d03c9a3f5d8e.jpeg)

Screenshot Chrome vom Laptop:
![unscharf-2](https://user-images.githubusercontent.com/48991539/114259586-4895f800-99cf-11eb-9e7b-45f6d88ab82f.PNG)

Auffäligkeit im Vis Editor: 
![unscharf-1](https://user-images.githubusercontent.com/48991539/114259598-61061280-99cf-11eb-8d84-f5788721c4b5.PNG)

Datenfeld Timestamp zeigt keinen Wert

![slideshow-objects](https://user-images.githubusercontent.com/48991539/114259607-7418e280-99cf-11eb-8159-ca724f38fb06.PNG)

Nach Drücken des Update Buttons: 

- Timestamp Date wieder vorhanden
- Schärfe wieder normal

![image](https://user-images.githubusercontent.com/48991539/114259644-bd693200-99cf-11eb-9051-1a3e2af0d68e.png)

![image](https://user-images.githubusercontent.com/48991539/114259662-d83ba680-99cf-11eb-8825-1fcc896f8892.png)

Log zeigt keine Auffälligkeiten.

**Comment by heymkeyu** [comment]
Der EXIF-Datenpunkt slideshow.0.date verliert offenbar auch unabhängig von dem Schärfe-Thema ab bestimmter Laufzeit seinen Inhalt und wird nicht pro Bild neu erzeugt. 

Auch hier: Drücken des Update Buttons behebt das Problem.

**Comment by gaudes** [comment]
@heymkeyu 
Wieviele Bilder von welcher Quelle hast Du ?

Wie gesagt, der Code ist immer genau der gleiche, da passiert also keine Änderung.

Was sich natürlich ändert ist das jeweilige Bild.

Meine Vermutung: Er kommt irgendwann an "alte" Bilder. Vermutlich ist die Auflösung bei denen nicht so gut, bzw. die EXIF-Daten fehlen ebenso. 

Kannst eines der betroffenen Bilder mal manuell und direkt in VIS einbinden, bzw. im Windows Explorer die EXIF-Daten prüfen ? Ich vermute, dass die EXIF-Daten fehlen und die Auflösung der betroffenen Bilder mangelhaft ist.

Wenn Du den Button drückst, dann wird die Liste der Bilder neu eingelesen. Er fängt danach also auch wieder von vorne in der Liste an.

**Comment by heymkeyu** [comment]
Anhand zweier Bilder, die in der Slideshow unscharf dargestellt wurden überprüft und im Dateisystem geöffnet: Die Bilder sind völlig in Ordnung und werden scharf im QNAP-Viewer dargestellt. 

Ich habe derzeit den Verdacht, dass beim Einlesen der Bilder in  den Datenpunkt slideshow.0.picture etwas schiefgeht, sodass die Auflösung nicht mehr korrekt ist. Die Auflösungen und Größen der Bilder im Bilderverzeichnis sind wie gesagt sehr unterschiedlich:

Da sind sehr kleine Panoramabilder dabei (~100kb) aber auch sehr große von der digitalen Spiegereflex, die anschließend gestitcht wurden mit > 20MB.

Ich versuche mal ohne diese Bilder zu testen und dann gezielt wieder mit, um zu sehen, ob es daran liegt.

**Comment by heymkeyu** [comment]
Merkwürdig: 
![image](https://user-images.githubusercontent.com/48991539/114315399-20a5b200-9aff-11eb-879c-3f8707739b51.png)
-> 4994 Bilder. 

![image](https://user-images.githubusercontent.com/48991539/114315424-3915cc80-9aff-11eb-930a-84b868eb1521.png)
-> 19968 pictures found in folder /opt/iobroker/slides ??

![image](https://user-images.githubusercontent.com/48991539/114315473-6e221f00-9aff-11eb-9350-1d4ab1b23078.png)
-> Timestamp leer. 

Darauf: einzelne Bilder unscharf

**Comment by heymkeyu** [comment]
Die Thumbnails hier dürften mein Problem sein: 
![image](https://user-images.githubusercontent.com/48991539/114317063-96614c00-9b06-11eb-9f02-f2a89a97856a.png)

**Comment by gaudes** [comment]
Nein, da gibt es keine Möglichkeit. Der Adapter geht halt davon aus, dass er alle Bilder im Pfad verwenden kann.

Das mit den Thumbnails klingt aber sehr plausibel für die schlechte Qualität und die fehlenden EXIF-Informationen.

**Comment by heymkeyu** [comment]
Die Thumbnails bzw. die entsprechenden Unterverzeichnisse sind für meinen Admin User übrigens nicht sichtbar.
ioBroker läuft im Docker Container auf der QNAP Container Station.

**Comment by heymkeyu** [comment]
Gar nicht so einfach das Thumbnail-frei hinzubekommen. Bisher ist es mir nicht gelungen. 
Ordner erzeugt, in dem die Thumbnaail-Generierung explizit deaktiviert ist. 
Bilder hineinkopiert: 
19968 pictures found in folder /opt/iobroker/slides-4992-nothumbs
(also 19968 anstelle 4992)

**Comment by heymkeyu** [comment]
Wäre schön, wenn es eine Option gäbe, die die Rekursion in Unterverzeichnisse unterbindet. 
Die Thumbnails wird man jedenfalls nicht spontan los und bisher ist es mir nicht gelungen. :-\

**Comment by gaudes** [comment]
Hmm ... Rekursion abschalten macht glaub in den wenigsten Fällen Sinn.

Das einzige was mir einfällt: Beschränkung auf eine Mindestgröße, ist aber nicht schön.

Hat QNAP da keine API analog zu Synology ?

**Comment by heymkeyu** [comment]
Kenne die Synologies nicht. 
Thumbnail-Generierung generell deaktivieren ist auch unschön. 
Muss mal noch weiter forschen.

**Comment by heymkeyu** [comment]
Ich geb's auf für heute. 
Alles deaktiviert, nochmals kopiert, aber dennoch: 19968 pictures found in folder /opt/iobroker/slides-4992-nothumbs

**Comment by gaudes** [comment]
Hast du zufällig Discord und Lust das mal gemeinsam anzuschauen ?

Ich habe keine QNAP, aber eventuell bieten die ja auch so eine API wie Synology.

Bei QNAP heißt es wohl auch PhotoStation. Wir müssten mit einem Browser (am besten Chrome) mal direkt auf die PhotoStation schauen.

**Comment by heymkeyu** [comment]
Ja, das Ding heisst Photostation - nutze ich allerdings nicht. sprich ist nicht sinnvoll eingerichtet.

Ich habe heute nochmals ein Verzeichnis mit gesammelten Bildern frisch zusammengestellt (PC->NAS). Alle anderen Tests waren bisher NAS->NAS.

Die Autogenerierung von Thumbnails ist wie oben geschrieben deaktiviert. Bisher klappt das. Keine zusätzlichen Files als Bilder erkannt. Bilder wie erwartet scharf und mit korrekten EXIF-Timestamps. 

Wenn das so bleibt "kann ich damit leben". ;-) 

Bin dennoch der Meinung man sollte für Filesystem zwei Dinge nachrüsten:

1. Option NICHT in Subdirectories nach Bildern zu suchen
2. Option der Dateigrößeneinschränkung von - bis

Damit muss man sich nicht mit all dem auseinandersetzen was die unterschiedlichen Flavors an NAS-Systemen so an Eigenheiten zu bieten haben.

**Comment by gaudes** [comment]
Ich würde maximal eine Mindestgröße für Bilder machen, damit kann mit die Thumbnails ja ausschließen.

Wie groß sind denn die bei Dir so ?

**Comment by heymkeyu** [comment]
Ich habe die Bilder ja testweise auf FHD skaliert. Das kleinste war dann knapp 100KB. 

Ich kann leider nicht sehen, wie groß die Thumbnail-Files selbst sind. 

Auch hilfreich wäre minmale height/witdh in Pixels - aber das dürfte schätzungsweise teurer als Filesize sein, oder?

**Comment by gaudes** [comment]
Nee, für height/width muss ich in jedes Bild "reinschauen", dass ist zu "teuer".

Minimum Filesize wäre eine Option, das sollte schon gehen.

Tendenziell will ich den Adapter aber auch nicht mit Optionen "überfrachten".

Wenn es OK ist würde ich den Issue erstmal liegen lassen und es dann bei mehreren Rückmeldungen einbauen ?

**Comment by heymkeyu** [comment]
> Wenn es OK ist würde ich den Punkt ins Backlog nehmen und erstmal liegen lassen und es dann bei mehreren Rückmeldungen einbauen ?

Klar, passt!
