### ISSUE TITLE
Feature Request: Scheduled Picture Update

### ISSUE THREAD

**Issue by jack-blackson** [gaudes/ioBroker.slideshow#41]
It would be great to have the possibility in the options of the adapter to choose if a scheduled update (every hour, every 6 hours,..) would be available.

Thanks,
Jack

**Comment by gaudes** [comment]
Hallo,
ich habe es gerade eingebaut. Bitte mal testen und Rückmeldung geben.
Es ist keine neue Version, also Aktualisierung über die Katze --> Beliebig und dann folgendes eingeben:

gaudes/ioBroker.slideshow#main

Bitte Rückmeldung ob es so klappt.

**Comment by jack-blackson** [comment]
Funktioniert gut für mich, danke!
