### ISSUE TITLE
Effects not working in Firefox

### ISSUE THREAD

**Issue by jack-blackson** [gaudes/ioBroker.slideshow#42]
Hello!

I was trying to find a nice effect to switch from one picture to another. I have chosen this setup:
<img width="235" alt="grafik" src="https://user-images.githubusercontent.com/13975634/114294158-df7cb600-9a9c-11eb-8a56-a27e7473c274.png">
When I do this in Firefox 87, it seems to not work correctly. During the picture change, it switches to one completely different picture for 1-2 seconds, and then jumps to the next one. The debug console shows this error:
<img width="902" alt="grafik" src="https://user-images.githubusercontent.com/13975634/114294248-8cefc980-9a9d-11eb-8622-820d1c111c7a.png">
Have I set it up incorrectly to get a smooth change?

**Comment by gaudes** [comment]
Hey,

I've used currently the JQuery function toggleClass.

This seems not to work 100%.

I've changed the code now and toggle the classes manual.

It's not a new version, so please update by the Github-Icon:

gaudes/ioBroker.slideshow#main

Please reply if it works now correct.

**Comment by jack-blackson** [comment]
I changed it to JQuery and fade, now the picture in between is gone, but I can't really see a transmission, it seems to be white for 1 sec and then the new picture appears..and the errors in the log are still there.

**Comment by gaudes** [comment]
Hey,

has it worked now with Transition ?

I've checked also the JQuery fade in Firefox 87, no error message here.

Maybe you should extend the "Übergangsphase" (transition time) to a minimum of 1000, 100 is a little bit short to see a transition.

Do you have other Javascript integrated ?  Can you check it with a new VIS project ?

**Comment by jack-blackson** [comment]
Ah - Transition now works fine, after I adjusted the transition time to 1000 - looks good :) Regarding the error in the console, still need to figure out if it is really comming from this widget or not.

**Comment by gaudes** [comment]
The source "PictureInPictureChild" is definitvly not from my Adapter :-)

**Comment by gaudes** [comment]
Hey @jack-blackson ,

did you find the source of the error message ?
Can I close this issue ?

Regards, Ralf

**Comment by jack-blackson** [comment]
Yes - seems to come from somewhere else, not from your adapter
