### ISSUE TITLE
Datenpunkte für interaktive Steuerungsmöglichkeit

### ISSUE THREAD

**Issue by heymkeyu** [gaudes/ioBroker.slideshow#43]
Hello. 

Ich wieder. :-) 

Weiss nicht, ob Du es nicht ohnehin schon im Backlog hast, aber ich fände folgende Features noch cool:

1. Datenpunkt "Reihenfolge" bei der Darstellung.

Für die Bildquellen Dateisystem oder Synology Photostation wäre diese Optionen nett, damit der Benutzer in der Visualisierung die gewünschte Reihenfolge einstellen kann, oder die Reihenfolge per Skript geändert werden kann. 
![image](https://user-images.githubusercontent.com/48991539/114445949-f6242980-9bd0-11eb-8b8a-60afeb2a832f.png)

2. Datenpunkte zur Steuerung Previous / Pause / Play / Next
für die jeweiligen Optionen zur interaktiven Steuerung in der Visualisierung

:-)

**Comment by gaudes** [comment]
Hi,

du weisst, jeder hat 3 frei danach wirds kostenpflichtig :-D

Zu 1.:
Sehe gerade nicht den wirklich den Vorteil es im laufenden Betrieb zu ändern. So muss man es halt einmal in den Adaptereinstellungen ändern ...

Zu 2.:
Glaub das hatte ich schonmal mit jemandem besprochen. Der Adapter soll ja mehr ein Bildschirmschoner sein. Die meisten Systeme wie Fernseher, Synology, QNAP, ... bieten ja bereits solch interaktive Möglichkeiten.
Diese Systeme können das auch "besser", da ich das Bild je nach Quelle erstmal in ioBroker laden muss und es dann der Browser darstellt. Man merkt auch schon eine kurze Verzögerung zwischen Änderung Datenpunkt und Umsetzung im VIS, auch wegen der Animationen. Mit Buttons wirds dann glaub unschön, da sich da dann die Verzögerung deutlicher bemerkbar macht.
Zweck ist ja eher auf einem Display ein paar nette Bilder anzuzeigen, solange die VIS nicht benötigt wird.

**Comment by heymkeyu** [comment]
> du weisst, jeder hat 3 frei danach wirds kostenpflichtig :-D

Ich liefere hier fantastische kostenlose Ideen, die den Wert des Produkts steigern! ;-)

**Comment by gaudes** [comment]
Wenn ich was für kriegen würde schon :-D

Ich habe beide Punkte mal ins Backlog genommen.

Der Adapter ist ja noch Beta, und wie gesagt will ich die Optionen auch nicht "überfrachten".

OK so ?

**Comment by heymkeyu** [comment]
Yes. Danke! :-)

**Comment by heymkeyu** [comment]
> Wenn ich was für kriegen würde schon :-D

Pack mal Deinen PayPal-Donation-Link ins readme. ;-)
