### ISSUE TITLE
Is this adapter still maintained? - PLEASE RESPOND UNTIL 31.12.2024 LATEST

### ISSUE THREAD

**Issue by mcm1957** [gaudes/ioBroker.slideshow#434]
Please let us know whether this adapter is still maintained by posting any reply comment.
Please fix issues #310 and #432 as soon as possible.

**If there is no reaction until 31.12.2024 this adapter will be removed from repositories.**

**Comment by gaudes** [comment]
Done

**Comment by mcm1957** [comment]
THANKS for your work
