### ISSUE TITLE
Bei Verwendung zweier Adapter-Instanzen geraten die Inhalte der jeweiligen Widgets durcheinander

### ISSUE THREAD

**Issue by heymkeyu** [gaudes/ioBroker.slideshow#44]
Szenario:
Ich habe eine Slideshow in /index.html#SlideShow, die tagsüber meine Bilderauswahl abspielt (heller Hintergrund, mit Visualisierungselementen)
In der View /index.html#NightMode hingegen wird nachts eine kleine Auswahl von Milchstraßenfotos dargestellt, die Inhalte der Visualisierung sind dabei mit dunklem Hintergrund stark reduziert

Die beiden Instanzen des Adapters sind (Dateisystem-Pfad) mit unterschiedlichen Einstellungen konfiguriert (Quell-Pfad, Wechselfrequenz).

Wechselt eine Adapter-Instanz das Bild, erscheint dieser Bildwechsel in beiden Instanzen - bedeutet: Die Views, deren Slideshow-Widgets mit unterschiedlichen Datenpunkten 
* slideshow.0.picture (15 Sekunden Update Intervall)
* slideshow.1.picture (Für Testzwecke: 5 Sekunden Update Intervall, normale Einstellung: 2 Minuten. Aufgetreten in Testeinstellung.)

verknüpft sind erhalten dennoch die Inhalte der jeweils anderen Adapter-Instanz.

**Comment by gaudes** [comment]
Hallo,
ich habe es gerade korrigiert. Bitte mal testen und Rückmeldung geben.
Es ist keine neue Version, also Aktualisierung über die Katze --> Beliebig und dann folgendes eingeben:

gaudes/ioBroker.slideshow#main

Bitte Rückmeldung ob es so klappt.

**Comment by heymkeyu** [comment]
Verhalten ist leider noch wie vorher. 

Update-Verlauf:
```

$ ./iobroker url "gaudes/ioBroker.slideshow#main" --debug
install gaudes/ioBroker.slideshow#main
NPM version: 6.14.4
npm install gaudes/ioBroker.slideshow#main --loglevel error --prefix "/opt/iobroker" (System call)
+ iobroker.slideshow@0.1.3updated 1 package in 47.979s

112 packages are looking for funding  run `npm fund` for details
upload [4] slideshow.admin /opt/iobroker/node_modules/iobroker.slideshow/admin/words.js words.js application/javascript
upload [3] slideshow.admin /opt/iobroker/node_modules/iobroker.slideshow/admin/style.css style.css text/css
upload [2] slideshow.admin /opt/iobroker/node_modules/iobroker.slideshow/admin/slideshow.png slideshow.png image/png
upload [1] slideshow.admin /opt/iobroker/node_modules/iobroker.slideshow/admin/index_m.html index_m.html text/html
upload [0] slideshow.admin /opt/iobroker/node_modules/iobroker.slideshow/admin/admin.d.ts admin.d.ts video/mp2t
Adapter "system.adapter.vis.0" restarted.
process exited with code 0
```

Nachzuvollziehen, wenn ich zwischen
/vis/index.html#NightMode
/vis/index.html#SlideShow
hin und herwechsle. 

Intervalle Bildwechsel 5sec vs. 15sec.

**Comment by gaudes** [comment]
Hi @heymkeyu 

Manchmal checkt er die Änderung nicht richtig im VIS.

Ich habe gerade eine neue Version 0.1.4 veröffentlicht, bitte damit mal probieren.

Eventuell noch iobroker upload slideshow machen falls es nicht klappt.

VG Ralf

**Comment by gaudes** [comment]
Hi @heymkeyu ,

hast Du es mit der neuen Version versucht ? Klappt es damit ?

VG Ralf

**Comment by heymkeyu** [comment]
Hi Ralf, 
sorry, hatte den Kommentar nicht gesehen.
Bisher nur kurz getestet. Sah soweit gut aus. 
Ich nehme die View nun produktiv (das war sie vorher wegen des Bugs nicht). Wenn ich noch was finde, mach ich das Issue wieder auf. 
Gruß,
Oli

**Comment by heymkeyu** [comment]
Ich denke das passt. Hätte schon längst auftreten müssen. 
Klasse! Danke!
