### ISSUE TITLE
V0.2.0 läuft unter js-controller 7.x nicht

### ISSUE THREAD

**Issue by Horgul123** [gaudes/ioBroker.slideshow#446]
Das Widget der Version 0.2.0 läuft unter js-controller 7.x nicht. Es werden sowohl im VIS Editor als auch in der Runtime Fehler angezeigt. Ich konnte nur auf Grund des Aufbaus meiner VIS diese nicht kopieren

**Comment by gaudes** [comment]
@Horgul123 : Es war noch ein Fehler drin. Ich habe noch kein js-controller 7.x, da dieser ja noch Beta ist.

Aber unter 6.x läuft es nun. Eventuell noch ein Upload machen.

**Comment by Horgul123** [comment]
geht. Dank dir!
