### ISSUE TITLE
FeatureRequest: Synology PhotoStation Album vorgeben

### ISSUE THREAD

**Issue by patti9000** [gaudes/ioBroker.slideshow#51]
Hi, 
Erstmal super Arbeit mit deinem Adapter.
Läuft bei mir soweit wunderbar.

Gibt es eine Möglichkeit die Fotoauswahl der Synology Photostation auf ein spezielles Album zu begrenzen?

Danke
mfg
Patti #

**Comment by gaudes** [comment]
Hi,

danke :-)

Demnächst erscheint ja DSM 7 mit dem neuen Synology Photos (oder wie das heißt).
Da ich noch nicht weiß wie sich die API dort verändert, wird es bei der Quelle Synology erstmal nix neues geben.

Es gibt aber einen einfachen Weg: Leg einen neuen Benutzer auf der Synology an und gib diesem in der PhotoStation nur auf die gewünschten Alben die Berechtigung.

Damit funktioniert es dann wunderbar :-)

VG Ralf

**Comment by patti9000** [comment]
Stimmt gute Idee.
Danke!
