### ISSUE TITLE
Error while using Bing Pictures

### ISSUE THREAD

**Issue by MeisterTR** [gaudes/ioBroker.slideshow#53]
```

slideshow.0 | 10543 | 2021-04-21 06:58:03.214 | error | Error occured: Unknown Error in Bing(updatePictureList/Download) [Error: read ECONNRESET] []
-- | -- | -- | -- | --
slideshow.0 | 10543 | 2021-04-21 06:58:02.954 | debug | [Bing] Picture list received
slideshow.0 | 10543 | 2021-04-21 06:58:02.718 | debug | [Adapter] UpdatePictureStoreTimer occured

```

**Comment by gaudes** [comment]
Hey,

is this error occuring frequently ? Or just one time ?

The error message looks like a connection problem (TCP/IP).

**Comment by gaudes** [comment]
@MeisterTR missed my question ?

Regards, Ralf

**Comment by MeisterTR** [comment]
this error comes everytime when he want to update the pic

**Comment by gaudes** [comment]
@MeisterTR This error seems to be a problem with the network connection.

I've just added more debugging.

Can you please upgrade from git to the latest changes ? Version number remains the same.

Then please set the adapter to debug.

I've made a debug output with a JSON. This JSON includes the complete picture list received by Bing with the URLs for download. Can you try to download one of the pictures manual from the ioBroker command line for example with curl ?

I'm using just a simple download with axios.

Or can you try a reinstallation (uninstall and new install) of the adapter ?

Regards, Ralf

**Comment by gaudes** [comment]
@MeisterTR 
Hi, any updates with the latest version?
Thanks and regards, Ralf
