### ISSUE TITLE
Instanz wird nicht angezeigt

### ISSUE THREAD

**Issue by Azathoth88** [gaudes/ioBroker.slideshow#54]
Ich habe den Adapter mehrfach in **Docker** installiert / deinstalliert - auch über direkt über GIT.
Leider wird mir keine Instanz angezeigt. Die Objekte fehlen ebenfalls.
In der Konsole wird mir mittels sudo iobroker update allerdings eine Installation bestätigt.
Adapter    "slideshow"     : 0.1.4    , installed 0.1.4

Unter iobroker-data\files konnte ich ebenfalls einen Ordner auffinden. Dieser verschwindet auch bei einer Installation.
Unter der VIS wird mir wiederum das Widget angezeigt. Es scheint aber nicht wirklich zu funktionieren.

Nun die entscheidene Frage:
Was ist zu tun, damit ich die Instanz korrekt installiert bekomme?
Ein Filterproblem in Richtung "Nur laufende Instanzen darstellen" ist es jedenfalls scheinbar nicht.

**Comment by Azathoth88** [comment]
Das Problem hat sich gelöst, nachdem ich den Adapter auf react UI umgestellt habe.

**Comment by gaudes** [comment]
Hi @Azathoth88 

wie Du hast den Adapter auf React UI umgestellt ?!

Admin 5 ?

VG Ralf

**Comment by Azathoth88** [comment]
Hallo,

mein Fehler. Der Satz hieße richtig:
Das Problem hat sich gelöst, nachdem ich den Admin-Adapter auf react UI umgestellt habe.
Demzufolge richtig erkannt: Admin v5

**Comment by HolgerGERMANY** [comment]
Hi - bei werden auch neuinstallierte Instanzen nicht angezeigt. Wenn es an dem react UI liegt - kann man mir verraten wie man das umstellen. Admin 6.4.2
