### ISSUE TITLE
set synology path?

### ISSUE THREAD

**Issue by MeisterTR** [gaudes/ioBroker.slideshow#55]
ist it possible to set a synology folder path?

**Comment by gaudes** [comment]
Hey @MeisterTR ,

currently not.

Current version of PhotoStation is the last release.

With DSM 7 there will be a complete version, probably with a different API.

So I will not make futher developments for the current release.

When DSM 7 is released as final version, I will take a look. I hope that Synology will document the API. The current version is undocumented. I've found an independent website with a self-made documentation which I used.

But there is a simple workaround already working:

Create a specialized user in DSM and give this user access only to the albums/folders in PhotoStation which should be shown.

Regards, Ralf
