### ISSUE TITLE
Feature Request: Support für Synology Photos

### ISSUE THREAD

**Issue by Azathoth88** [gaudes/ioBroker.slideshow#56]
Die PhotoStation wird mit DSM 7 durch Synology Photos ersetzt.  Entsprechend wäre eine Integration von Photos wünschenswert.

**Comment by gaudes** [comment]
Hi @Azathoth88 

werde ich mir anschauen wenn DSM 7 final ist. Ich habe nur eine Synology zu Hause und will da keine Beta laufen haben.

Leider gab es schon für die bisherige PhotoStation keine Doku der API. Jemand hatte sich die Mühe gemacht und diese auseinandergenommen und auf einer Webseite dokumentiert.

Ich schau es an sobald DSM 7 final ist.

VG Ralf
