### ISSUE TITLE
Feature Request: Bilder aus Netzwerk beziehen

### ISSUE THREAD

**Issue by Azathoth88** [gaudes/ioBroker.slideshow#57]
Es wäre schön, wenn man die Fotos aus einem Netzwerkverzeichnis (z.B. über SMB) einbinden könnte.

**Comment by gaudes** [comment]
Hi @Azathoth88 

das Problem ist, dass ioBroker mittlerweile diverse Betriebssysteme unterstützt.

In jedem Betriebssystem funktioniert der Mount bzw. das Verbinden von Netzlaufwerken komplett anders. Je nach Betriebssystem müssen auch noch weitere Voraussetzungen (z.B. Samba) installiert sein.

Daher werde ich das aufgrund des Aufwands nicht einbauen.

Was aber natürlich geht: Du kannst das Mapping bzw. den Mount selbst in deinem Betriebssystem vornehmen.

Unter Linux z.B. kann man ja den Mount-Pfad selbst festlegen.

Diesen Pfad kannst Du dann problemlos in der Konfig verwenden.

VG Ralf
