### ISSUE TITLE
rezise Bilder

### ISSUE THREAD

**Issue by MeisterTR** [gaudes/ioBroker.slideshow#58]
ich hab bis vor kurzem ein selbst erstelltes Skript genutzt. Welches die Bilder noch an die Bildschirmgröße angepasst hat. wenn die Originale alle über 4 MB haben ist das schon eine ganz schöne last für den Rechner und mach das Frontend träge

```
const resizeImg = require('resize-img');

            if ((img.width / img.height) >= (width / height)) {
                prop = img.width / width
            } else {
                prop = img.height / height
            }
const newImage = await resizeImg(pic, {
                width: parseInt(img.width/prop) ,
                height: parseInt(img.height/prop)
            });
```

**Comment by jack-blackson** [comment]
Bei welchen Quellen wird es gecacht? Ich finde die Idee eigentlich gut - ich nutze es über Synology, und fände es schade, dort die Bilder immer vorher herunterrechnen zu müssen. Wäre schon cool wenn der Adapter das macht - event. als Option? Ich merke auch das je nach Bildgröße es bei der Ausgabe stockt. Event. könnte das immer gemacht werden, wenn die Bilder aktualisiert werden?

**Comment by gaudes** [comment]
Aktuell nur bei Bing. Diese lade ich vorher alle in einen Ordner runter.

Was verwendest denn für ein Ausgabe-Device ? Muss sagen, am Echo Show merke ich davon nichts.

Je nach Animation sind im Widget zwei <img ..> Tags vorhanden, wovon eines unsichtbar ist. Beim Bildwechsel wird das neue Bild in das unsichtbare Widget geladen. Erst wenn der Ladevorgang fertig ist wird das unsichtbare img mittels Animation sichtbar. Daher bemerke ich bei der Anzeige eigentlich keinerlei Verzögerung.
