### ISSUE TITLE
Feature Request: add control buttons

### ISSUE THREAD

**Issue by jack-blackson** [gaudes/ioBroker.slideshow#59]
I think it would be nice to have possibilities to control the slideshow - with a "play/pause", "next" and "back" button. This can help to freeze a picture, if for some time you want to stay with this picture, or if you want to jump back to see the one before again.

**Comment by gaudes** [comment]
Hello,

after having no time for development a very long time I've just pushed new version 0.2.0 with a few changes.

Start/stop control buttons included :-)

Kind regards

Ralf
