### ISSUE TITLE
Link to Readme from Admin not working

### ISSUE THREAD

**Issue by jack-blackson** [gaudes/ioBroker.slideshow#85]
When I check the adapter in the admin, click on the readme and open it in the new tab, it shows " Not Found" and doesn't link to the read me. In the "preview", before open it in a new tab, it works fine.

Version: 0.1.4

**Comment by gaudes** [comment]
Hi @jack-blackson 

which version of admin ? Which browser ?

I'm using Google Chrome and it works when I right click the blue question mark icon and then choose "open in new tab".

I can only make one link to the readme in the io-package.json file and this link is correct. The rest of the functionallity is made by admin adapter.

Regards, Ralf

**Comment by jack-blackson** [comment]
Admin is 4.2.1, Browser is Firefox. 

Step 1:
<img width="356" alt="grafik" src="https://user-images.githubusercontent.com/13975634/121077471-f3f8d880-c7d7-11eb-9108-8046405ffe10.png">
Step 2:
<img width="681" alt="grafik" src="https://user-images.githubusercontent.com/13975634/121077531-0410b800-c7d8-11eb-84a5-2a33a74b0c50.png">
Step 3:
<img width="938" alt="grafik" src="https://user-images.githubusercontent.com/13975634/121077581-13900100-c7d8-11eb-9db5-354d3379f5e3.png">

It seems that the URL looks different. yours shows https://github.com/gaudes/ioBroker.slideshow/main/README.md, e.g. the one from the backitup adapter looks like this: https://github.com/simatec/ioBroker.backitup/blob/master/README.md. Don't know if this makes the difference.

**Comment by gaudes** [comment]
OK, I can retrace this problem.

I've made an issue in Admin adapter:

https://github.com/ioBroker/ioBroker.admin/issues/982

I will close this issue here.

**Comment by gaudes** [comment]
Hi @jack-blackson 

problem in Admin Adapter has been solved, but only for the new 5.x version.

See issue here:

ioBroker/ioBroker.admin#982

Regards, Ralf
